### ISSUE TITLE
Enable All / Disable All Option

### ISSUE THREAD

**Issue by marcelnem** [willmendesneto/ngx-feature-toggle#189] opened 2019-06-25 13:27 UTC
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
```

**Current behavior**

Now I have to copy paste the whole configuration for all possible environments.

**Expected behavior**

It would be nice to have an option to enable all features. For example I would develop a service which would return true every time for any feature name if the url of the loaded webpage is localhost. If the url is different the service would return the value for a given feature from the config object. If there is no value for that feature name, the service would return false.

Or I would like to have a button in the application "hide all development features" and after this button is clicked, my service would return false for any features, otherwise it would always return true for all the features. then I do not need the config object at all. 

Summary - the API expects a config object always, this is too restrictive.

(maybe I misunderstood th API, if yes , then I am sorry)
 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX |
  Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

  

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

- **Node (if applicable):** `node --version` =

**Comment by willmendesneto** [comment] 2019-07-03 11:49
Hi @marcelnem , thanks for the issue.

This module is not covering this scenario by design, that was a conscious decision. It doesn't have this feature because it can increase the bundle for at least 80% of users who don't need this feature. 

Instead of adding it into this module, we can add this logic at the top wrapper who's passing down the feature toggle attributes and adding them on `<feature-toggle-provider [features]="featureToggleData">` component. So this wrapper can check for the dev environment and do it straight away.

```js
export class AppComponent  {
  // Feature Toggle list to be added into 
  // `<feature-toggle-provider>` component
  featureToggleData: any = {
    enableFirstText: false,
    enableSecondText: true
  };

  constructor() {
    // Logic to check if it is production of not.
    // Change it with the app logic if needed
    const isProd = false;
    if (!isProd) {
      this.turnOffFeatureToggle();
    }
  }

  turnOffFeatureToggle(): void {
      Object.keys(this.featureToggleData).forEach(key => {
        this.featureToggleData[key] = false;
      });
  }
}
```

I wrote a StackBlitz example with this scenario. So we can add it quickly into the consumer side, being a consumer in that scenario any type of web app. Feel free to check this link and play with that.

https://stackblitz.com/edit/ngx-feature-toggle-sample-wv5wud?file=app%2Fapp.component.ts

**Comment by willmendesneto** [comment] 2019-07-21 09:33
Closing this issue for now. Feel free to open again if required.

**Closed by willmendesneto** 2019-07-21 09:33 UTC
