### ISSUE TITLE
FeatureToggleProvider  does not work with RxJS

### ISSUE THREAD

**Issue by humbertosales** [willmendesneto/ngx-feature-toggle#155] opened 2018-01-10 21:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
Nothing! The FeatureToggleProvider   ignore featureToggleService=RxJS (subscribe)

**Expected behavior**
Listening RxJS (subscribe) and use data response.

**Reproduction of the problem**

**Partial HTML**
```html
                <feature-toggle-provider [featureToggleService]="featureService.getAllFeatures()"></feature-toggle-provider>
                <feature-toggle [featureName]="'categoria'">
                  <button type="button" class="btn btn-danger btn-sm" (click)="excluirCategoria(categoria)">
                    <i class="fa fa-remove"></i>
                  </button>
              </feature-toggle>

```

**MyComponent and MyService (RxJS)**
```typescript
export class CategoriaHomeComponent implements OnInit {
    constructor(private featureService: FeatureService) {            }
...
}

export class FeatureService {

  constructor(private http: HttpClient) {
  }

  public getAllFeatures(): Observable<any> {
    return this.http.get<any>(API_URL + '/features');
  }

  public get(key: String): Observable<Boolean> {
    return this.http.get<Boolean>(API_URL + '/features/' + key);
  }
}
```

**Comment by willmendesneto** [comment] 2018-03-15 12:32
Hello @humbertosales .

thanks for open this issue. Looks like, based on you example, the issue is related to your component structure.

If you look at the [examples on README.md](url) and on [`feature-toggle-provider.component.spec.ts` tests](https://github.com/willmendesneto/ngx-feature-toggle/blob/master/src/spec/feature-toggle-provider.component.spec.ts#L11..L22) `feature-toggle-provider` should wrap `feature-toggle` component.

```html

<feature-toggle-provider [featureToggleService]="featureService.getAllFeatures()">
  <feature-toggle [featureName]="'categoria'">
    <button type="button" class="btn btn-danger btn-sm" (click)="excluirCategoria(categoria)">
      <i class="fa fa-remove"></i>
    </button>
  </feature-toggle>
</feature-toggle-provider>
```

Can you check if this behavior still persists using the latest version of `ngx-feature-toggle`, please?

**Comment by willmendesneto** [comment] 2018-03-18 13:52
Closing this issue by lack of reply

**Closed by willmendesneto** 2018-03-18 13:52 UTC

**Comment by robert-king** [comment] 2022-06-07 03:50
i think he's trying to say that the feature flags aren't reactive variables, i.e. you can't update the flags during runtime using http requests because feature-toggle-provider [featureToggleService] does not accept an observable or promise. One option is to use a resolver on any component that needs flags, another option is to provide default flags while loading the flags, neither option is great IMO.
